
spring:
  profiles:
    include: oauth

  datasource:
    # RDS MariaDB
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dietblog.c8hynnw3dhnt.ap-northeast-2.rds.amazonaws.com:3306/dietblog
    username: dogyun
    password: kdk519437

  # Local MySQL
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/knuDietBlog?serverTimezone=UTC&characterEncoding=UTF-8
#    username: dogyun
#    password: 1234

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create

<<<<<<< HEAD
    generate-ddl: true
    show-sql: true
=======
    generate-ddl: false
    show-sql: false
>>>>>>> dda0e35cdeb60d4335432faa77e2c6026e4683da
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: \home\ec2-user\app\images
      max-file-size: 100MB
      max-request-size: 100MB

file:
  dir: \home\ec2-user\app\images\   # 실제 파일을 저장할 곳
