# 보안상의 이유로 프로젝트에 대한 설정만 저장한다.
# 보안과 관련된 설정은 서버에 따로 저장해둔다.
# DB 접속 아이디, 비밀번호, Oauth 인증 토큰 등등..

spring:
  profiles:
    include: oauth,db     # include하면 application-* 이름의 파일이 포함됨.
  
  session:
    store-type: jdbc

  # PUT, DELETE 메소드를 사용할려면 활성화해주어야 함.
  mvc:
    hiddenmethod:
      filter:
        enabled: on

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: C:\Users\kdk12\Desktop\file
      max-file-size: 100MB
      max-request-size: 100MB

file:
  dir: C:\Users\kdk12\Desktop\file\   # 실제 파일을 저장할 곳
