spring:
  profiles:
    include: oauth,real-db
  jpa:
    hibernate:
      ddl-auto: create

    generate-ddl: true
    show-sql: true


    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
<<<<<<< HEAD
        format_sql: true

session:
=======
  session:
>>>>>>> dda0e35cdeb60d4335432faa77e2c6026e4683da
    store-type: jdbc

file:
  dir: \home\ec2-user\app\images\   # 실제 파일을 저장할 곳
