spring:
  datasource:
    # 실제 서비스 DB (AWS RDS)
#    url: jdbc:mariadb://dietblog.c8hynnw3dhnt.ap-northeast-2.rds.amazonaws.com:3306/dietblog
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: dogyun
#    password: kdk519437

    # 테스트용 DB (H2 Database)
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: create


