
spring:
  profiles:
    include: oauth
  
  session:
    store-type: jdbc

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: \home\ec2-user\app\images
      max-file-size: 100MB
      max-request-size: 100MB

file:
  dir: \home\ec2-user\app\images\   # 실제 파일을 저장할 곳
